### PR TITLE
Add truck description and phone number

### PR DESCRIPTION
**Pull request by MariusVolkhart**
@jault3 @maconsuckow @atscott @moorea @nockertsb

### CODE REVIEW

**Comment by atscott** [comment]
While we're at it, can we change the modify request to take a truck instead of all the parameters? This might have been changed to allow for us to ignore the imageUrl though. 
https://github.com/TruckMuncher/TruckMuncher-Protos/blob/description/com/truckmuncher/api/trucks.proto#L99

**Comment by MariusVolkhart** [comment]
@atscott it was indeed https://github.com/TruckMuncher/TruckMuncher-Protos/commit/c0419fe021d97c9d0b21379e10c007f91e4b54cf

Though I see how this is going to become annoying rather quickly...

**Comment by MariusVolkhart** [comment]
I also don't remember _why_ that change was required

**Comment by atscott** [comment]
It's a really big workflow issue since saving the image is actually a separate API call.

**Comment by MariusVolkhart** [comment]
Ah ok. I mean, we could have the modify request have a truck and ignore the value of the imageUrl but that's not very intuitive and I think would be a source for bugs.

We also have to deal w/ backwards compatibility a bit now since we have apps in the wild. What would be the optimal scenario for modifying for the web?

**Comment by atscott** [comment]
Well it doesn't matter a huge amount, but it would be nice to have an object rather than tons and tons of parameters. I'm fine either way.

**Comment by jault3** [comment]
:shipit:

**Pull request merged**
